"""initial migration

Revision ID: 5b7162b5d1bd
Revises: 
Create Date: 2026-02-12 12:04:23.124468

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7162b5d1bd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('campaigns', sa.Column('purpose', sa.Text(), nullable=False))
    op.add_column('campaigns', sa.Column('image_url', sa.String(length=500), nullable=False))
    op.alter_column('campaigns', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('campaigns', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('campaigns_ngo_id_fkey'), 'campaigns', type_='foreignkey')
    op.create_foreign_key(None, 'campaigns', 'ngos', ['ngo_id'], ['id'], ondelete='CASCADE')
    op.add_column('milestones', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('milestones', sa.Column('order_number', sa.Integer(), nullable=False))
    op.alter_column('milestones', 'title',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('milestones', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_constraint(op.f('milestones_campaign_id_fkey'), 'milestones', type_='foreignkey')
    op.create_foreign_key(None, 'milestones', 'campaigns', ['campaign_id'], ['id'], ondelete='CASCADE')
    op.drop_column('milestones', 'collected_amount')
    op.add_column('ngos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('ngos', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('ngos', sa.Column('description', sa.Text(), nullable=False))
    op.add_column('ngos', sa.Column('registration_number', sa.String(length=100), nullable=False))
    op.add_column('ngos', sa.Column('address', sa.Text(), nullable=False))
    op.add_column('ngos', sa.Column('phone', sa.String(length=50), nullable=False))
    op.add_column('ngos', sa.Column('website', sa.String(length=255), nullable=True))
    op.add_column('ngos', sa.Column('trust_score', sa.Integer(), nullable=True))
    op.add_column('ngos', sa.Column('campaign_count', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('ngos_email_key'), 'ngos', type_='unique')
    op.create_unique_constraint(None, 'ngos', ['user_id'])
    op.create_foreign_key(None, 'ngos', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('ngos', 'password')
    op.drop_column('ngos', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ngos', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('ngos', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ngos', type_='foreignkey')
    op.drop_constraint(None, 'ngos', type_='unique')
    op.create_unique_constraint(op.f('ngos_email_key'), 'ngos', ['email'], postgresql_nulls_not_distinct=False)
    op.drop_column('ngos', 'campaign_count')
    op.drop_column('ngos', 'trust_score')
    op.drop_column('ngos', 'website')
    op.drop_column('ngos', 'phone')
    op.drop_column('ngos', 'address')
    op.drop_column('ngos', 'registration_number')
    op.drop_column('ngos', 'description')
    op.drop_column('ngos', 'name')
    op.drop_column('ngos', 'user_id')
    op.add_column('milestones', sa.Column('collected_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'milestones', type_='foreignkey')
    op.create_foreign_key(op.f('milestones_campaign_id_fkey'), 'milestones', 'campaigns', ['campaign_id'], ['id'])
    op.alter_column('milestones', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('milestones', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('milestones', 'order_number')
    op.drop_column('milestones', 'description')
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.create_foreign_key(op.f('campaigns_ngo_id_fkey'), 'campaigns', 'users', ['ngo_id'], ['id'])
    op.alter_column('campaigns', 'target_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('campaigns', 'title',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('campaigns', 'image_url')
    op.drop_column('campaigns', 'purpose')
    op.drop_column('campaigns', 'description')
    # ### end Alembic commands ###
