"""sync code and database

Revision ID: f675ecae4205
Revises: b556d557d13e
Create Date: 2026-02-22 22:24:25.445085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f675ecae4205'
down_revision: Union[str, Sequence[str], None] = 'b556d557d13e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_tokens_token_hash'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.alter_column('campaigns', 'raised_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('donations', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donations', 'milestone_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('donations', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('donations', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('donations', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('donations_transaction_id_key'), 'donations', type_='unique')
    op.create_index(op.f('ix_donations_id'), 'donations', ['id'], unique=False)
    op.create_index(op.f('ix_donations_transaction_id'), 'donations', ['transaction_id'], unique=True)
    op.drop_constraint(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_user_id_fkey'), 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_donations_transaction_id'), table_name='donations')
    op.drop_index(op.f('ix_donations_id'), table_name='donations')
    op.create_unique_constraint(op.f('donations_transaction_id_key'), 'donations', ['transaction_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('donations', 'is_anonymous',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('donations', 'amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('donations', 'transaction_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('donations', 'milestone_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('donations', 'campaign_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('campaigns', 'raised_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('password_reset_tokens_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('password_reset_tokens_pkey'))
    )
    op.create_index(op.f('ix_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###
